name: Deploy Website to S3

on:
  push:
    branches:
    - main
    #paths:
    #- dist/ggordonvi/**

jobs:
  deploy:
  #build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        #SOURCE_DIR: 'deploy'      # optional: defaults to entire repository

    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Setup Node v18
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Build Application
      run: npm run build:prod

    - name: Deploy Application
      run: aws s3 sync ./dist/ggordonvi s3://ggordonvi.com